version: "3.4"

# Put environment, ports and other PRODUCTION only information here

services:
  # Other
  identity.svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80

  apigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 80

  # Databases
  bm.db:
    environment:
      POSTGRES_PASSWORD: example

  acc.db:
    environment:
      POSTGRES_PASSWORD: example

  # APIs
  bm.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 80

  acc.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 80
