version: '3.4'

services:
  businessmanagementDB:
    image: postgres
  businessmanagementservice:
    image: businessmanagementservice
    build:
      context: .
      dockerfile: src/BusinessManagementService/Dockerfile
    ports:
      - 80
      - 443
  accountservice:
    image: accountservice
    build:
      context: .
      dockerfile: src/AccountService/Dockerfile
    ports:
      - 80
      - 443
  imagetestservice:
    image: imagetestservice
    build:
      context: .
      dockerfile: src/ImageTestService/Dockerfile
    ports:
      - 80
      - 443
  imagestoreservice:
    image: imagestoreservice
    build:
      context: .
      dockerfile: src/ImageStoreService/Dockerfile
    ports:
      - 80
      - 443
  robotservice:
    image: robotservice
    build:
      context: .
      dockerfile: src/RobotService/Dockerfile
    ports:
      - 80
      - 443