version: '3.4'
# FOR DEBUGGING ONLY!
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: accountservice
    ports:
      - "5432:5432"

  app:
    image: accountservice
    build:
      context: ../
      dockerfile: AccountService/Dockerfile
    ports:
      - "1337:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db