// <auto-generated />
using System;
using BusinessManagementService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BusinessManagementService.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessManagementContext))]
    [Migration("20200509090723_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BusinessManagementService.Domain.AggregatesModel.AnalysisProfileAggregate.AnalysisProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("_description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("_fileName")
                        .HasColumnName("filename")
                        .HasColumnType("text");

                    b.Property<string>("_name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("analysisprofiles");
                });

            modelBuilder.Entity("BusinessManagementService.Domain.AggregatesModel.AnalysisProfileAggregate.AnalysisProfileRequiredFeature", b =>
                {
                    b.Property<Guid>("AnalysisProfileID")
                        .HasColumnName("analysisprofileid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureID")
                        .HasColumnName("featureid")
                        .HasColumnType("uuid");

                    b.HasKey("AnalysisProfileID", "FeatureID");

                    b.HasIndex("FeatureID");

                    b.ToTable("analysisprofilerequiredfeatures");
                });

            modelBuilder.Entity("BusinessManagementService.Domain.AggregatesModel.BusinessTierAggregate.BusinessTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("_name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("businesstiers");
                });

            modelBuilder.Entity("BusinessManagementService.Domain.AggregatesModel.FeatureAggregate.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("_description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("_name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("features");
                });

            modelBuilder.Entity("BusinessManagementService.Domain.AggregatesModel.AnalysisProfileAggregate.AnalysisProfileRequiredFeature", b =>
                {
                    b.HasOne("BusinessManagementService.Domain.AggregatesModel.AnalysisProfileAggregate.AnalysisProfile", "AnalysisProfile")
                        .WithMany("RequiredFeatures")
                        .HasForeignKey("AnalysisProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessManagementService.Domain.AggregatesModel.FeatureAggregate.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
