version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management

  apigw:
    image: apigw
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 80
      
  bm.db:
    image: postgres

  bm.api:
    image: bm.api
    build:
      context: .
      dockerfile: BusinessManagementService/Dockerfile
    ports:
      - 80
    depends_on:
      - bm.db
      - rabbitmq

  acc.db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: accountservice

  acc.api:
    image: acc.api
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    ports:
      - 80
    depends_on:
      - acc.db
